settings:
  title: 'SRVFI探针'
  url: 'https://status.srvfi.top/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '全部系统在线'
  notAllmonitorsOperational: '部分系统宕机'
  monitorLabelOperational: '在线'
  monitorLabelNotOperational: '宕机'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 次失败(s)' # xx incident(s) recorded

monitors:
  - id: www-srvfi-top # unique identifier
    name: 'SRVFI主站'
    url: 'https://www.srvfi.top/login.php' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true

  - id: ptgen-srvfi-top
    name: 'ptgen服务'
    url: 'https://ptgen.srvfi.top/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: www-svfi-group
    name: 'svfi文档'
    url: 'https://doc.svfi.group/'
    method: GET
    expectStatus: 200
    linkable: true
    followRedirect: true
