settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-srvfi-top # unique identifier
    name: www-srvfi-top
    description: '主站' # default=empty
    url: 'https://www.srvfi.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ptgen-srvfi-top
    name: ptgen-srvfi-top
    description: 'ptgen服务'
    url: 'https://ptgen.srvfi.top/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: www.svfi.group
    name: 'svfi文档'
    url: 'https://www.svfi.group/'
    method: GET
    expectStatus: 200
