settings:
  title: 'SVFI探针'
  url: 'https://status.svfi.group/' # used for Slack messages
  logo: SVFI.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '全部系统在线'
  notAllmonitorsOperational: '部分系统宕机'
  monitorLabelOperational: '在线'
  monitorLabelNotOperational: '宕机'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 次失败(s)' # xx incident(s) recorded

monitors:
  - id: www-svfi-doc
    name: 'svfi文档'
    url: 'https://doc.svfi.group/'
    method: GET
    expectStatus: 200
    linkable: true
    followRedirect: true

  - id: www-svfi-server-main
    name: 'svfi主服'
    url: '45.88.194.116:23333/svfi_ctrl'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false

  - id: www-svfi-server-backup
    name: 'svfi备服'
    url: '101.43.116.157:23333/svfi_ctrl'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false
