# wrangler.toml
name = "cf-workers-status-page-production"
compatibility_date = "2024-01-01"
main = "src/index.js"

[[kv_namespaces]]
binding = "KV_STATUS_PAGE"
id = "31c3570dff95403e8c905f473003c12e"

[triggers]
crons = ["*/2 * * * *"]

[build]
command = "npm run build"

[assets]
directory = "./dist"